# This file was generated by GoReleaser. DO NOT EDIT.
cask "semantica" do
  version "0.3.8"

  on_macos do
    on_intel do
      sha256 "9357e9f99dc9537abc6b67e0fb7a5cd2a360c38724b66780f195bf13870daf36"
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2281e9e1a9324838d65ded57e73628f69ca57829b4835a2c78f8f532961e74b8"
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1cf8bac91cd75d485f8159c408b8297638e96c734e41ee5f29b3e9dc8c234e2f"
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00530fc69acddcf73818635f6c950fe3f2354406bd2ba1762cc0dbc23df5435e"
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_arm64.tar.gz"
    end
  end

  name "semantica"
  desc "Observability and control for AI-assisted development"
  homepage "https://www.semantica.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semantica"
  bash_completion "completions/semantica.bash"
  fish_completion "completions/semantica.fish"
  zsh_completion "completions/semantica.zsh"

  # No zap stanza required

end
