# This file was generated by GoReleaser. DO NOT EDIT.
cask "semantica" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_amd64.tar.gz"
      sha256 "2a44b71cd0899d617efd59b32875325868426361b2c23cde3cd53f310bcc8eb5"
    end
    on_arm do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_arm64.tar.gz"
      sha256 "fb3f4050d2670a9b0683c9565bea89da13a0fee35daebcea9d4ac5dcef3e396d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_amd64.tar.gz"
      sha256 "0bebc65fb00e03c0ce2f10cc2e6cf3de69889e8098f1b579f57ce6b023359ab9"
    end
    on_arm do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_arm64.tar.gz"
      sha256 "3108dba4364aaa9b16393d92219485c26a34d03bdf48408c3ec67e2a09d9d032"
    end
  end

  name "semantica"
  desc "Observability and control for AI-assisted development"
  homepage "https://www.semantica.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semantica"
  bash_completion "completions/semantica.bash"
  fish_completion "completions/semantica.fish"
  zsh_completion "completions/semantica.zsh"

  # No zap stanza required

end
