# This file was generated by GoReleaser. DO NOT EDIT.
cask "semantica" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_amd64.tar.gz"
      sha256 "46862c6baf529589c28500e614089160a7b4413ed2473f497f8d9bc6e3a998c9"
    end
    on_arm do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_darwin_arm64.tar.gz"
      sha256 "71cab0c1f0b9b286f1eebb8207f453fb8b5f3f719e5d51011370b037bce5e14e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_amd64.tar.gz"
      sha256 "c06441cd28bff579242c1959e62668a452225ff4d63b724850305302abc606cb"
    end
    on_arm do
      url "https://github.com/semanticash/cli/releases/download/v#{version}/semantica_linux_arm64.tar.gz"
      sha256 "da265da39b384972a08c7253069940fb67e538863e8fe67feddf53b34ced14fc"
    end
  end

  name "semantica"
  desc "Observability and control for AI-assisted development"
  homepage "https://www.semantica.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semantica"
  bash_completion "completions/semantica.bash"
  fish_completion "completions/semantica.fish"
  zsh_completion "completions/semantica.zsh"

  # No zap stanza required

end
